### ISSUE TITLE
On / Off works now yay

### ISSUE THREAD

**Issue by icepicknz** [DirtyDevWork/homebridge-daikin#15]
Appears to work now; what are the commands to use on Siri any idea?
Turn on bedroom aircon now works, but does anyone know how to control heat, aircon, fan and for a specific temperature?

cheers

**Comment by icepicknz** [comment]
still crashes after time; get this error

[10/29/2016, 4:49:26 AM] [Bedroom Aircon] setTargetHeatingCoolingState from/to:3/0
[10/29/2016, 4:49:26 AM] [Bedroom Aircon] State: 0
[10/29/2016, 4:49:26 AM] [Bedroom Aircon] Temp: 21
[10/29/2016, 4:49:26 AM] [Bedroom Aircon] Temp: 21
[10/29/2016, 4:49:26 AM] [Bedroom Aircon] State: 0
[10/29/2016, 4:49:26 AM] [Bedroom Aircon] setDaikinMode: setting pow to ?pow=0, mode to &mode=4 and stemp to &stemp=21
[10/29/2016, 4:49:26 AM] [Bedroom Aircon] response success
[10/29/2016, 4:49:26 AM] [Bedroom Aircon] body: ret=OK,adv=
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect EHOSTUNREACH 192.168.44.51:1400
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)

**Comment by DirtyDevWork** [comment]
Siri commands I've found work:
"Turn on/off the heater" - Daikin on/off to heat to current target temperature
"Turn on/off the cooler" - Daikin on/off to cool to current target temperature
"Set the temperature to X degrees" - Sets the Daikin's target temperature in Celsius

For some reason "Turn the Heater on to X degrees" doesn't work, not sure yet if that is a HomeKit bug, HomeBridge limitation or something I can fix in this plugin

**Comment by DirtyDevWork** [comment]
I haven't seen that error thrown yet on either of my HomeBridge instances. How long is your HomeBridge running before that happens?

**Comment by DirtyDevWork** [comment]
@icepicknz, Still getting that crash? I haven't yet managed to replicate it. Any info will help
