### ISSUE TITLE
Need data from other models of Daikin systems and controllers

### ISSUE THREAD

**Issue by DirtyDevWork** [DirtyDevWork/homebridge-daikin#5]
Post the returned values from GET /common/basic_info, /aircon/get_model_info, /aircon/get_control_info, /aircon/get_sensor_info, and feature list of your Daikin system here to help inclusion in this plugin in the future

**Comment by icepicknz** [comment]
ret=OK,type=aircon,reg=th,dst=1,ver=2_9_0,pow=0,err=0,location=0,name=%44%61%69%6b%69%6e%41%50%37%32%35%30%39,icon=0,method=polling,port=30050,id=000102ss,pw=u52bwjpi,lpw_flag=0,adp_kind=2,pv=2,cpv=2,cpv_minor=00,led=1,en_setzone=1,mac=60F189CAF0D1,adp_mode=run,en_hol=0,grp_name=,en_grp=0

ret=OK,model=0C88,type=N,pv=2,cpv=2,cpv_minor=00,mid=NA,humd=0,s_humd=0,acled=0,land=0,elec=0,temp=1,temp_rng=0,m_dtct=1,ac_dst=--,disp_dry=0,dmnd=0,en_scdltmr=1,en_frate=1,en_fdir=1,s_fdir=3,en_rtemp_a=0,en_spmode=0,en_ipw_sep=0,en_mompow=0

ret=OK,pow=0,mode=4,adv=,stemp=24.0,shum=0,dt1=25.0,dt2=M,dt3=18.0,dt4=24.0,dt5=24.0,dt7=25.0,dh1=AUTO,dh2=50,dh3=0,dh4=0,dh5=0,dh7=AUTO,dhh=50,b_mode=4,b_stemp=24.0,b_shum=0,alert=255,f_rate=4,f_dir=0,b_f_rate=4,b_f_dir=0,dfr1=5,dfr2=5,dfr3=4,dfr4=4,dfr5=4,dfr6=5,dfr7=5,dfrh=5,dfd1=0,dfd2=0,dfd3=0,dfd4=0,dfd5=0,dfd6=0,dfd7=0,dfdh=0

ret=OK,htemp=21.0,hhum=-,otemp=16.0,err=0,cmpfreq=0

**Comment by travellingnashes** [comment]
ret=OK,type=aircon,reg=eu,dst=1,ver=2_6_0,pow=0,err=0,location=0,name=%42%65%64%72%6f%6f%6d,icon=0,method=polling,port=30050,id=000002n2,pw=jfbbfanu,lpw_flag=0,adp_kind=2,pv=2,cpv=2,cpv_minor=00,led=1,en_setzone=1,mac=784B8719DCE9,adp_mode=run,en_hol=0,grp_name=,en_grp=0

ret=OK,model=0ABB,type=N,pv=2,cpv=2,cpv_minor=00,mid=NA,humd=0,s_humd=0,acled=0,land=0,elec=0,temp=1,temp_rng=0,m_dtct=1,ac_dst=--,disp_dry=0,dmnd=0,en_scdltmr=1,en_frate=1,en_fdir=1,s_fdir=3,en_rtemp_a=0,en_spmode=0,en_ipw_sep=0

ret=OK,pow=0,mode=4,adv=,stemp=22.0,shum=0,dt1=25.0,dt2=M,dt3=25.0,dt4=22.0,dt5=22.0,dt7=25.0,dh1=AUTO,dh2=50,dh3=0,dh4=0,dh5=0,dh7=AUTO,dhh=50,b_mode=4,b_stemp=22.0,b_shum=0,alert=255,f_rate=A,f_dir=0,b_f_rate=A,b_f_dir=0,dfr1=5,dfr2=5,dfr3=5,dfr4=A,dfr5=A,dfr6=5,dfr7=5,dfrh=5,dfd1=0,dfd2=0,dfd3=0,dfd4=0,dfd5=0,dfd6=0,dfd7=0,dfdh=0

ret=OK,htemp=21.0,hhum=-,otemp=14.0,err=0,cmpfreq=0

**Comment by travellingnashes** [comment]
BTW version I have just posted fails with : {"ret":"OK,htemp":"21.0,hhum":"-,otemp":"14.0,err":"0,cmpfreq":"0"}
                 ^

SyntaxError: Unexpected token :
    at Object.parse (native)
    at Object.<anonymous> (/Users/nashm/.nvm/versions/node/v5.0.0/lib/node_modules/homebridge-daikin/index.js:225:21)
    at Request.self.callback (/Users/nashm/.nvm/versions/node/v5.0.0/lib/node_modules/homebridge-daikin/node_modules/request/request.js:187:22)

**Comment by DirtyDevWork** [comment]
@travellingnashes, which version of the plugin are you running?

**Comment by DirtyDevWork** [comment]
Ah, well getting the same error on the current version. Looks like my script converting the response from the Daikin to JSON is leaving out occasional quotation marks. I'll open an issue to track progress fixing that

**Comment by icepicknz** [comment]
Thanks for that, i'll look out for a response; is it normal behaviour to cause the whole home bridge to crash rather than just error for the task?

**Comment by travellingnashes** [comment]
Latest 0.5 ?

Thanks

Mike

Mike Nash
...................................

Mobile : +44 7843326139

**Comment by DirtyDevWork** [comment]
@icepicknz It isn't, but for the moment I'd recommend comment out the Daikin accessory info from HomeBridge's config.json file.
I'm going to update the Readme on NPM to instruct people not to use it quite yet unless they want to fork it to troubleshoot it themselves

@travellingnashes Thanks for that, please comment out the accessory section for Daikin for the moment and I'll update you when it is done. If you're interested in watching the progress, keep an eye on Issue #8

**Comment by DirtyDevWork** [comment]
@icepicknz @travellingnashes just letting you know this issue is resolved as of version 0.0.10, but it cannot change modes and power for the Daikin, only reads sensors and mode info from the Daikin.
It's late so I'm calling it a night and will be back getting it all up and able to control the Daikin in about 9 hours or so. Thanks for your help nailing these ones down so far!

**Comment by mbnn** [comment]
Here you go for my Daikin Unit from 2012 with Wifi adapter:

ret=OK,type=aircon,reg=eu,dst=1,ver=2_6_0,pow=0,err=0,location=0,name=%57%6f%6f%6e%6b%61%6d%65%72,icon=2,method=polling,port=30050,id=tcaircoliving,pw=w1rl2y7s,lpw_flag=0,adp_kind=2,pv=0,cpv=0,cpv_minor=00,led=1,en_setzone=1,mac=FCC2DE451618,adp_mode=run,en_hol=0,grp_name=,en_grp=0

ret=OK,model=NOTSUPPORT,type=N,pv=0,cpv=0,mid=NA,s_fdir=1,en_scdltmr=1

ret=OK,pow=0,mode=1,adv=,stemp=21.0,shum=0,dt1=21.0,dt2=M,dt3=25.0,dt4=25.0,dt5=25.0,dt7=21.0,dh1=0,dh2=50,dh3=0,dh4=0,dh5=0,dh7=0,dhh=50,b_mode=1,b_stemp=21.0,b_shum=0,alert=255,f_rate=A,f_dir=0,b_f_rate=A,b_f_dir=0,dfr1=A,dfr2=5,dfr3=5,dfr4=5,dfr5=5,dfr6=5,dfr7=A,dfrh=5,dfd1=0,dfd2=0,dfd3=0,dfd4=0,dfd5=0,dfd6=0,dfd7=0,dfdh=0

ret=OK,htemp=18.0,hhum=-,otemp=-,err=0,cmpfreq=0

**Comment by DirtyDevWork** [comment]
Thanks @mbnn, looking at what you're getting back from your system, I'm pretty sure it should be working already. Have you tried the plugin yet?

@icepicknz and @travellingnashes, what Model is your Air Conditioner? Just so I can keep track.

**Comment by mbnn** [comment]
You are right :) It seems to work completely! Thank you!

**Comment by DirtyDevWork** [comment]
@mbnn, can you just check that you can set temperatures in all modes and switch on and off, let me know if any of those throw and unusual messages for homebridge?

**Comment by mbnn** [comment]
I have tried cool, heat, auto, off and temperature settings and it all seems to work for me :)

**Comment by travellingnashes** [comment]
I have a Daikin Emura II

**Comment by DirtyDevWork** [comment]
@mbnn, I noticed that too. I think it's a HomeKit thing, because the Daikin isn't listed as having a switch characteristic (so no plain On and Off). I may be able to get that to behave that way in the future, I'll look into it later on.

@travellingnashes, thanks for the info. Is it working with On/Off, modes and temperature setting at the moment?

**Comment by ghost** [comment]
Evening,

Any plans to support Daikin units that respond to requests that look like this:

http://192.168.x.xx:2000/ac.cgi?pass=XXXXX  ?

Note that this request returned: 

opmode=0&units=.&settemp=24.0&fanspeed=1&fanflags=1&acmode=8&tonact=0&toffact=0&prog=0&time=10:10&day=6&roomtemp=25&outsidetemp=24&louvre=1&zone=0&flt=0&test=0&errcode=&sensors=1


More info on the request parameters here: http://forums.whirlpool.net.au/archive/2440219

Looks like the parameters are different to the ones this homebridge-daikin module currently supports so may be a big job. Happy to help if I can.
 
Update: I have taken a copy of the code and I am looking to add support for Daikin SKYFi. Looks straight forward and so I confident I can do it ...

Update 2: Done it! I have my other unit which is has a SKYFi interface working through the Home app. Not as easy as I had thought. Basically a rewrite of this module's .js as the http commands sent to the unit are so different and my unit hates two commands to be sent at the same time.  Thinking that I will create a new GIT project rather than merge the branch unless anyone wants to take on the merge?

**Comment by ghost** [comment]
Response from my other Daikin unit (which is on and cooling) as follows:

common/basic_info -> ret=OK,type=aircon,reg=th,dst=1,ver=2_9_0,pow=1,err=0,location=0,name=%44%61%69%6b%69%6e%41%50%39%33%30%30%36,icon=0,method=polling,port=30050,id=XXXXXX,pw=XXXXXX,lpw_flag=0,adp_kind=2,pv=2,cpv=2,cpv_minor=00,led=1,en_setzone=1,mac=XXXXXX,adp_mode=run,en_hol=0,grp_name=,en_grp=0

aircon/get_model_info -> ret=OK,model=0C8B,type=N,pv=2,cpv=2,cpv_minor=00,mid=NA,humd=0,s_humd=0,acled=0,land=0,elec=0,temp=1,temp_rng=0,m_dtct=1,ac_dst=--,disp_dry=0,dmnd=0,en_scdltmr=1,en_frate=1,en_fdir=1,s_fdir=3,en_rtemp_a=0,en_spmode=0,en_ipw_sep=0,en_mompow=0

aircon/get_control_info -> ret=OK,pow=1,mode=3,adv=,stemp=24.0,shum=0,dt1=25.0,dt2=M,dt3=24.0,dt4=25.0,dt5=25.0,dt7=25.0,dh1=AUTO,dh2=50,dh3=0,dh4=0,dh5=0,dh7=AUTO,dhh=50,b_mode=3,b_stemp=24.0,b_shum=0,alert=255,f_rate=A,f_dir=3,b_f_rate=A,b_f_dir=3,dfr1=5,dfr2=5,dfr3=A,dfr4=5,dfr5=5,dfr6=5,dfr7=5,dfrh=5,dfd1=0,dfd2=0,dfd3=3,dfd4=0,dfd5=0,dfd6=0,dfd7=0,dfdh=0

aircon/get_sensor_info -> ret=OK,htemp=25.0,hhum=-,otemp=34.0,err=0,cmpfreq=34
